apiVersion: dj.dysproz.io/v1
kind: DaemonJob
metadata:
  name: daemonjob-sample
spec:
  template:
    spec:
      containers:
        - name: test-job
          image: busybox
          command:
            - sleep
            - "20"
      nodeSelector:
        app: v1
      restartPolicy: OnFailure
